### ISSUE TITLE
Spreadsheet Size

### ISSUE THREAD

**Issue by doguhanokumus** [jpillora/node-edit-google-spreadsheet#61]
Hi again,

It's now over a week I'm getting used to this library and most of my script is using automated flow and at the initialization of a document I'm having a small problem.

When the script run, let's say I have 50 columns to send, but the document has only 30 columns. I'm getting errors in this case regarding cell_id does not exist, which is a correct warning.

I can manually add columns and cells into the Sheet, but it could be a cool feature if this library could **auto-expand** the sheet so that my 'updates' could fit into the sheet.

**Comment by jofomah** [comment]
try

spreadsheet.send( [options,] callback( err ) )

Sends off the batch of add()ed cells. Clears all cells once complete.

options.autoSize When required, increase the worksheet size (rows and
columns) in order to fit the batch - *NOTE: When enabled, this will trigger
an extra request on every send()* (default false).


spreadsheet.send({autpSize: true}, callback)

**Comment by doguhanokumus** [comment]
Thank you @jofomah and I'm sorry that I skipped it at the documentation.

In my case, since I need it only at initialization of a document (i.e. importing the headers), I'm actually calling it only once for each page without any rows.
